openstax/cnx-db

- cnxdb/cli/common.py
- cnxdb/cli/discovery.py
- cnxdb/cli/main.py
- cnxdb/cli/subcommands.py
- cnxdb/init/__init__.py
- cnxdb/init/exceptions.py
- cnxdb/init/main.py
- cnxdb/tests/cli/scanned_import/module1.py
- cnxdb/tests/cli/scanned_import/module2.py
- cnxdb/tests/cli/test_discovery.py
- cnxdb/tests/cli/test_main.py
- cnxdb/tests/conftest.py
- cnxdb/tests/init/test_main.py
- cnxdb/tests/testing.py
- docs/index.rst
- setup.py
This creates the entry-point for the ``cnx-db`` script which contains two commands: ``init`` and ``venv``. These commands initialize the database and (re-)initialize the virtual environment (a.k.a. venv) within the database.
> Command Line Interface to initialize the database schema and virtual environment

- MANIFEST.in
To fix this error:
```
Traceback (most recent call last):
File "/home/travis/build/Connexions/cnx-archive/cnxarchive/tests/transforms/test_resolvers.py", line 295, in setUp
self.fixture.setUp()
File "/home/travis/build/Connexions/cnx-archive/cnxarchive/tests/testing.py", line 74, in wrapped
return method(self, cursor, *args, **kwargs)
File "/home/travis/build/Connexions/cnx-archive/cnxarchive/tests/testing.py", line 176, in setUp
super(DataFixture, self).setUp()
File "/home/travis/build/Connexions/cnx-archive/cnxarchive/tests/testing.py", line 159, in setUp
init_db(self._settings[config.CONNECTION_STRING], True)
File "/home/travis/build/Connexions/cnx-archive/.eggs/cnx_db-0.2.0-py2.7.egg/cnxdb/init/main.py", line 53, in init_db
for schema_part in get_schema(SCHEMA_DIR):
File …
```
> Include cnxdb/schema/*.* in the package

- tox.ini
This will only install mock for python<=2.7
> Install mock during test environment setup

- cnxdb/archive-sql/schema/functions.sql
- cnxdb/archive-sql/schema/indexes.sql
- cnxdb/publishing-sql/schema-indexes.sql
These are needed to address some performance issues with fetching individual document metadata.
> create ident_hash functions and associated indexes

- Makefile
- cnxdb/archive-sql/schema/triggers.sql
- cnxdb/tests/cli/test_main.py
- cnxdb/tests/conftest.py
- cnxdb/tests/init/test_main.py
- cnxdb/tests/schema/test_triggers.py
- cnxdb/tests/testing.py
- requirements/tests.txt
- setup.cfg
This will now send the module_ident and ident_hash as part of the
notification. This will allow listeners/subscribers to use this detailed
information to take action on the event rather than query for the data
after a blank notification.
> Notify post_publication with payload

- cnxdb/migrations/20170510185646_post_publication_with_payload.py
This adds a migration for the addition of the post_publication notification
payload.
> Add post_publishing trigger function migration

- cnxdb/migrations/20170530143035_search-modtags-index.py
Since we hand deployed this index to solve a critical performance issue, this needs to be guarded so as not to error. fixes #28 updating code merged in #27
> make migration conditional

- cnxdb/archive-sql/search/query.sql
currently errors if a chapter gets matched. Some day, may want to return chapters, but this will do for first release.
> Don't return chapters (subcollections) in search

- cnxdb/migrations/20170530185035_switch_to_channel_processing.py
- cnxdb/publishing-sql/schema-tables.sql
Drop the `post_publications` table in favor of a simple association table for the baking process. This associates the `modules.module_ident` with the `results_id` of a `celery.results.AsyncResult`, which may or may not be stored in the same database depending on how celery has been configured to store the results.
> Add association table for celery results to modules

- cnxdb/migrations/20170821163229_update_latest_trigger.py
cursor.exeucte -> cursor.execute
> Fix typo in migration update_latest_trigger

- cnxdb/migrations/20170811000000_minor-version-correction.py
- cnxdb/migrations/20170812000000_current-modules-view.py
Clean up some issues w/ production data, and correct the logic used in the current_modules view. That view and the trigger-maintained latest_modules should always be identical, by design. The view is used by one trigger (the delete_from_latest trigger on the modules table) to refill latest if the latest version of a given document is deleted. A rare event, but needs coverage.
It occurs to me that the policy I defined above, as well as "latest_modules is to be maintained by triggers only  - all DML occurs on modules table" should probably be written down somewhere.
> fix minor versions and current_modules view

- .travis_test_migrations.sh
If the current branch is the same as master, there is nothing to test so
we can exit the script.
> Exit migration test script if branch is master

- cnxdb/archive-sql/schema/legacy/triggers.sql
- cnxdb/migrations/20170912141914_derived-ruleset-trig.py
When a collection/book has a derived copy made (in legacy), we need to copy any existing `ruleset.css`, so it maintains the same baked style. For now. This code can go away once print_style-based recipe selection is deployed (in AW 1.1)
> trigger for duplicating ruleset.css for derived copies

- cnxdb/migrations/20170911200000_update_index_cnxml.py
For modules that have both index.cnxml and index_auto_generated.cnxml,
pick the one with the higher cnxml version and store it as index.cnxml
and remove index_auto_generated.cnxml.
> Add migration to update index.cnxml

- cnxdb/migrations/20170815141631_subcol-uuids-fn.py
We ran the migration on QA and got this error:
```
Traceback (most recent call last):\n
File \"/var/cnx/venvs/publishing/bin/dbmigrator\", line 11, in <module>\n
sys.exit(main())\n
File \"/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/cli.py\", line 104, in main\n
return args['cmmd'](**args)\n
File \"/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/utils.py\", line 145, in wrapper\n
return func(cursor, *args, **kwargs)\n
File \"/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/commands/migrate.py\", line 32, in cli_command\n
run_deferred)\n
File \"/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/utils.py\", line 227, in compare_schema\n
callback(*args, **kwargs)\n
File …
```
> Use super user to replace plpythonu function in migration

- cnxdb/migrations/20170912134157_shred-colxml-uuids.py
We're seeing this error when deploying to QA:
```
Traceback (most recent call last):\n
File \"/var/cnx/venvs/publishing/bin/dbmigrator\", line 11, in <module>\n
sys.exit(main())\n
File \"/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/cli.py\", line 104, in main\n
return args['cmmd'](**args)\n
File \"/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/utils.py\", line 145, in wrapper\n
return func(cursor, *args, **kwargs)\n
File \"/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/commands/migrate.py\", line 32, in cli_command\n
run_deferred)\n
File \"/var/cnx/venvs/publishing/local/lib/python2.7/site-packages/dbmigrator/utils.py\", line 227, in compare_schema\n
callback(*args, **kwargs)\n
File …
```
> Use super user to create plpythonu function in migration

- cnxdb/migrations/20170918181635_rebake-double-trigger.py
Code to fix double-trigger-when-rebaking was committed a month ago, without a migration. This is the matching migration. Because the code is already on master, this will fail the migration test script, since old_schema == new_schema
> migration for code to fix double trigger when rebaking

- cnxdb/archive-sql/get-in-collated-book-search-full-page.sql
When attempting to get matches from the current page, current code returns every page with a match as if it was on the current page.
> in-collated-book page search over-match

- cnxdb/migrations/20170816204849_subcol-uuid-data.py
Ensuring the batch size is at least one prevents: `ValueError: range() step argument must not be zero`
If the batch is empty, the loop won't run, thus it won't declare `elapsed`.
The later fix is to prevent: `UnboundLocalError: local variable 'elapsed' referenced before assignment`
> Correct errors in subcol uuid migration associated with an empty batch

- cnxdb/migrations/20160723123620_add_sql_function_strip_html.py
- cnxdb/migrations/20160723124137_add_modules_strip_html_name_index.py
- cnxdb/migrations/20170201213850_add-subcollection-metadata.py
- cnxdb/migrations/20170208213802_ident-hash-func.py
- Create plpython function with super user in migration
When running the migrations 20160723123620_add_sql_function_strip_html,
20170201213850_add-subcollection-metadata,
20170208213802_ident-hash-func against a database where
the user is not a super user, we see this error:
```
psycopg2.ProgrammingError: permission denied for language plpythonu
```
- Create extension pg_trgm with super user in migration
When running the migration 20160723124137
add_modules_strip_html_name_index against a database where the user is
not a super user, we see this error:
```
psycopg2.ProgrammingError: permission denied to create extension "pg_trgm"
```
> Use postgres super user in migrations that require it

- cnxdb/archive-sql/schema/shred_collxml.py
- cnxdb/migrations/20170922150407_shred-collxml-stateid.py
- cnxdb/migrations/shred_collxml_20170922150407_pre.sql
avoids trying to bake them - they "fail fast (no recipe)" but fill up the status view page with noise.
> don't copy stateid from collection when inserting subcollections

- cnxdb/archive-sql/schema/fulltext-indexing.sql
- cnxdb/archive-sql/schema/functions.sql
- cnxdb/archive-sql/schema/indexes.sql
- cnxdb/archive-sql/schema/tables.sql
- cnxdb/migrations/20170911201035_transform_cnxml_to_html.py
- cnxdb/migrations/20170926023421_remove-lexeme-tables.py
- cnxdb/migrations/20170926044408_book-fulltext-index.py
- cnxdb/migrations/20170926045602_book-fulltext-index-data.py
- cnxdb/migrations/20170926132743_sha1-functions.py
- tests/schema/test_triggers.py
This PR does 3 things:
1. create book fulltext vector (full text index) from the component vectors of the pages that book contains
2. improve lexeme counting for in book search by using `ts_stat` funtion, instead of a prebuilt table. This removes a nasty string-parsing hack from the publishing path, as well as removing a couple tables from the DB.
3. missing functions (`sha1`) that are in the production DB, as well as migrations, but never were added to the base schema.
> Book fulltext search

- cnxdb/archive-sql/schema/triggers.sql
Somehow, a mis-match between the schema and migrations slipped
through. This mini-PR fixes just the schema to match the as-deployed
code, which matches the existing migration in
20170614211640_print-style-recipes
> BUGFIX - print_style_recipe update trigger

- cnxdb/archive-sql/schema/tables.sql
- cnxdb/archive-sql/schema/triggers.sql
- cnxdb/migrations/20171009211647_fix-print-style.py
- cnxdb/migrations/20171010195430_install-recipes.py
- requirements/test.txt
- script/ci_test_migrations.sh
- commit id for those who like that sort of thing
- title for human readable name of print style
Fixes up the triggers for maintaining default_print_style as well.
Note that the migration test will not pass for two reasons: we managed to deploy mismatched schema vs. migrations  - the trigger as written in schema is not valid, but was corrected in the migration. I did not write the rollback to install the invalid trigger function. And two, the new schema and the migrated schema differ in column order for the tables that we add columns to. The text diff of pg_dump output would be difficult to make aware of this difference. This is a known behavior of postgresql. I don't want to bow to this implementation detail by adding all new columns at the end: we have an SQL policy of not depending on …
> Add migration for print_style_recipes

- cnxdb/archive-sql/schema/triggers.sql
- cnxdb/archive-sql/schema/views.sql
- cnxdb/migrations/20170926215729_latest-logic.py
We has some clock-skew on staging (and production!) servers. which brought this to light. Note that the change to current_modules already has a migration, but I failed to put it in the regular installation. The migration test script would have caught that.
> do not use timestamps to determine latest content

- cnxdb/archive-sql/get-in-book-search-full-page.sql
- cnxdb/archive-sql/get-in-book-search.sql
- cnxdb/archive-sql/get-in-collated-book-search-full-page.sql
- cnxdb/archive-sql/get-in-collated-book-search.sql
- cnxdb/archive-sql/schema/functions.sql
- cnxdb/migrations/20171012130959_inbook-search-or-terms.py
Another in the series of "Ross can't fall asleep, so might as well code something" PRs
Was thinking about search. Now that it's possible to find books with terms that appear on different pages, it would be nice if doing the same search inside the book actually found and highlighted all of them.
> make in book search OR terms, rather than AND them

- cnxdb/archive-sql/schema/triggers.sql
- cnxdb/migrations/20171012231938_fix-update-latest-trigger.py
We changed the condition for adding modules to the latest_modules table
from just comparing the "revised" field to comparing the major and minor
versions:
```
ARRAY [NEW.major_version, NEW.minor_version] >= (
SELECT ARRAY [major_version, minor_version]
FROM latest_modules WHERE uuid = NEW.uuid)
```
This works ok when the uuid is found in the latest_modules table, it
doesn't work when the uuid doesn't exist.  For example:
```
cnxarchive=# SELECT 1 WHERE ARRAY [2, NULL] >= (
cnxarchive-#     SELECT ARRAY [major_version, minor_version] FROM latest_modules WHERE 1 = 0);
?column?
----------
(0 rows)
```
It appears `ARRAY [2, NULL] >= NULL` is false.  To fix this, adding
`UNION ALL SELECT ARRAY[0, NULL] LIMIT 1` seems to work.
> Fix update latest trigger not adding new modules

- tox.ini
This needs added in order to install our package requirements. Technically the setup.py does this, but we also want the requirements file to pin if necessary.
> Correct project testing requirements to also use main.txt

- cnxdb/archive-sql/get-in-book-search-full-page.sql
- cnxdb/archive-sql/get-in-book-search.sql
- cnxdb/archive-sql/get-in-collated-book-search-full-page.sql
- cnxdb/archive-sql/get-in-collated-book-search.sql
Further discussion w/ QA leads me to believe that "OR" is not the best default for in book search. This provides a parameter to select the combining boolean, defaulting to "AND"
> provide query_type parameterization for AND vs OR queries in-book-search

- docs/changes.rst
`doc8` reported that the lines under v0.11.0 in docs/changes.rst are too
long:
```
docs/changes.rst:12: D001 Line too long
docs/changes.rst:14: D001 Line too long
```
Sorry :bowing_woman:
> Wrap lines in docs/changes.rst

- setup.cfg
Just a small fix to ignore the dist directory. I believe I made this commit before the build directory was on this line, which is why the commit still says "build and dist".
> Ignore linting of build and dist directories

- .coveragerc
- .travis.yml
- setup.cfg
- tox.ini
This removes general coverage from a plain `pytest` command run, but it will do the right thing for `make test` (tox run) and travis.
This is a different approach to what #93 attempts to solve.
> Correct code coverage configuration

- cnxdb/config.py
- cnxdb/contrib/pyramid.py
- cnxdb/scripting.py
- docs/api.rst
- requirements/test.txt
- setup.py
- tests/cli/test_main.py
- tests/contrib/test_pyramid.py
- tests/test_config.py
This adds a contrib module for pyramid integration to be used as `config.include('cnxdb.contrib.pyramid')`.
Depends on #97
> Add Pyramid integration 

- tests/cli/test_main.py
- tests/test_config.py
- tests/test_scripting.py
The bahavior of mock.patch.dict is to mock clone the existing value and overlay with the given dict. I wasn't aware of this cloning behavior when I wrote it.
> Fix the env var test mocking

- cnxdb/contrib/pytest.py
- cnxdb/contrib/testing.py
- tests/init/test_main.py
This is being fixed because one might be in a venv, but not want to connect to the database as virtualenv importable.
This could not make sense, but for my usecase it works. I'm within a venv but running the tests through a container mounted with the local code. The container is not setup to work with a venv, because it doesn't need to be. This change simply brings both scenarios into a compatible use via the existing `AS_VENV_IMPORTABLE` environment variable.
> Fix virtualenv importable tests to skip if told

- cnxdb/contrib/testing.py
- setup.py
- tests/cli/test_main.py
- tests/contrib/test_pyramid.py
- tox.ini
These are fixes to enable the usecase of running the tests against a cnx-db container with the local code mounted into the container.
Please see the extended commit message for information about each commit.
The last commit to remove the 'pyramid' dependency is slipped in. 'pyramid' is not required for this project.
> Fix various tests to enable use with a container

- cnxdb/config.py
- cnxdb/scripting.py
- docs/changes.rst
- docs/config.rst
- tests/contrib/test_pyramid.py
- tests/test_config.py
- tests/test_scripting.py
This is to be used for operations that only required read access from the database. This means we can configure the application to use the write connections ('common') only when necessary.
We already have a setup that utilizes the replicants for known read-only operations. This now enables the developer to use the correct connection type for the given context.
> Add a read-only database setting and engine

- cnxdb/config.py
- docs/changes.rst
- tests/test_config.py
This fixes an issue when a set of settings is given and the env vars are not set. This ensure that we use the given value for the `db.common.url` setting in place of the missing DB_URL rather than leave it `None`, which would set the defaults for the other urls to `None` as well.
> Fix settings discover to use given settings if necessary

- cnxdb/contrib/pyramid.py
- docs/changes.rst
- tests/contrib/test_pyramid.py
This gives the pyramid application access to the sqlalchemy reflected tables, which can then be used in conjunction with sqlalchemy core features.
> Add a tables spec lookup to the pyramid contrib module

- cnxdb/migrations/20171130213038_recipe-primary-key.py
This will not pass migration test - rollback is to the actual current broken state, not to what cnx-db-init gives. Original code and migration predated the migration tests.
> migration for fixing primary key on print_style_recipe table

- cnxdb/archive-sql/schema/constants/modulestates.sql
- cnxdb/archive-sql/schema/triggers.sql
- cnxdb/archive-sql/schema/views.sql
- cnxdb/migrations/20171101193127_handle-fallback-state.py
This is needed to properly handle baked content that uses the fallback recipe. @kerwinso found it when testing swapping print_styles between with and w/o recipe.
> Handle fallback state

- cnxdb/contrib/pytest.py
We use sqlalchemy to initialize our database, that includes setting a
function that is run at the beginning of every session (what init_venv
does).  But sqlalchemy engines have connection pools that are already
connected, so virtualenv is not set up correctly for those connections,
causing the triggers to not be able to find the cnx code.
> Recreate connection pool after init_venv in tests

- cnxdb/contrib/pytest.py
- cnxdb/contrib/testing.py
- docs/changes.rst
- tests/cli/test_main.py
- tests/init/test_main.py
- Massage testing fixtures to better facilitate testing in packages using
this package.
- Provide additional init and wipe fixtures scoped at the module level.
- Remove custom function for table name lookup. Replaced by sqlalchemy
Inspector methods.
- Add a ``db_tables`` pytest fixture that supplies sqlalchemy table objects.
> Add module level testing fixtures to better facilitate testing in dependent packages

- cnxdb/archive-sql/get-module-metadata.sql
- docs/changes.rst
Adding the baked status to the return for get-module-metadata. The baked status is used in determining whether or not to cache in cnx-archive.
Connected to: https://github.com/Connexions/cnx-archive/pull/542
> add baked to get-module-metadata

- .dockerfiles/initdb.d/00_initdb.sh
- Dockerfile
- docker-compose.yml
- docs/changes.rst
These are fixes to address starting an empty cnx-db container. We added the feature to consume a slim dump, which works great, but missed the creation of a vanilla database.
I'm kind of surprised the tests didn't catch this, but I do believe as we move more tests into this package that will be covered.
The first commit addresses the issue with the condition to run `cnxdb init`. The second removes what I believe is now a redundant setting.
> Fix the empty container story

- cnxdb/archive-sql/schema/shred_collxml.py
- cnxdb/migrations/20180408175622_amend_shred_collxml_to_insert_latest_column_value.py
- cnxdb/migrations/20180408181936_make_everything_republishable.py
- cnxdb/migrations/shred_collxml_20180408175622_pre.sql
- docs/changes.rst
This fixes the collxml shredder to insert a value for ``trees.latest``. This also contains a migration to set all the current records to ``trees.latest = true``.
Fixes #120
> Fix collxml shredder to insert trees.lastest value

- requirements/test.txt
The release of ``pip==10.0.0`` changed some behavior with our requirements.txt files. In this case the fault is on us and partially on the new release. The requirements lines that point at git repos aren't prefixed with `-e`, which makes them editable installs and thus reinstallable. The new release is at fault for raising an error rather than saying something to the effect of "the requirement is satisfied and won't upgrade."
See pypa/pip#5251
> Fix requirements file with editable flag for vcs requirements

- cnxdb/contrib/pyramid.py
- cnxdb/contrib/testing.py
- docker-compose.yml
- docs/changes.rst
- docs/usage.rst
- requirements/test.txt
- tests/contrib/test_pyramid.py
Transition the following Pyramid integration properties:
``registry.engines`` and ``registry.tables``. These are now moved to
``request.get_db_engine()`` and ``request.db_tables()``.
This favors the recommended pattern of using request methods
for hooking into the current thread local variable space.
> Rename api points for Pyramid contrib module

- .dockerignore
- .gitignore
Just adds a ``.dockerignore`` file similar to ``.gitignore``.
> Ignore env build state and python dist and build directories in docker

- docs/changes.rst
- docs/usage.rst
This simply aligns the pyramid integration docs with the implementation.
> Correct the documentation to align with the implementation

- cnxdb/triggers/transforms/resolvers.py
- docs/changes.rst
- tests/triggers/transforms/test_resolvers.py
This corrects the issue (that wasn't created as an issue 😠) with where resource files with filenames that start with the module id were being stripped of the moduleid text. This happened because the reference path regex matches for all references not just resources.
The fix is to lookahead for url like markers. If the reference doesn't contain those markers we can assume it's a resource filename.
The first commit makes the existing regex pretty and verbose. The second commit actually fixes the issue.
> Do not strip the first part of resource name if it contains a module id

- cnxdb/archive-sql/get-module-head-version.sql
This is the most-recent-published-but-not-necessarily-latest version, since we redefined `latest` to mean `latest successfully baked for presentation`
> provide access to head version 

- .travis.yml
- cnxdb/archive-sql/get-collated-content.sql
Speeds up this query (which seems to run twice for all book content) from ~2 seconds to a few milliseconds by allowing it to use the existing ident_hash() index. Should help improve book load times on CNX and possibly overall CNX archive performance.
> Fixed the get-collated-content query so it uses the existing ident_hash index

- cnxdb/archive-sql/get-available-languages-and-count.sql
Archive tests were failing on OS X due to the lack of ordering for the languages.
> Order available languages query for consistent results

- Dockerfile
This was failing to reliably upgrade pip. The system pip was raising an
ImportError after the upgrade, which resulted in the dependencies not being
installed
> docker: fix pip upgrade commands

- cnxdb/archive-sql/schema/fulltext-indexing.sql
- cnxdb/archive-sql/schema/functions.sql
- cnxdb/archive-sql/schema/indexes.sql
- cnxdb/archive-sql/search/quick-wrapper.sql
- cnxdb/migrations/20180724165111_add-latest-modules-indices.py
- cnxdb/migrations/20180724183730_modify-index-fulltext-trigger.py
- cnxdb/migrations/20180803144633_drop-extra-gist-index.py
Rewrote the index_fulltext_trigger so that it can set different weights to tsvectors based on whether they are generated on titles, keywords, or texts.
> Add indices and modify a trigger

- cnxdb/archive-sql/schema/triggers.sql
- cnxdb/migrations/20180810152112_html-abstracts.py
This adds an explicit trigger to modules to transform the associated abstract, if only a cnxml version is available.
> add trigger to transform abstracts to html from cnxml

- .travis.yml
- cnxdb/archive-sql/schema/functions.sql
- cnxdb/migrations/20180816211433_dumpable-functions.py
- script/ci_test_dump_restore.sh
use explicit namespace in functions calls from functions used for indexes
This was causing failure to dump the db. Don't know why production can currently dump: perhaps psql 9.4.X can dump, but >9.5 triggers the problem? 
I want to add tests that dump and restore the DB after init. No need for test data.
Upstream links:
https://stackoverflow.com/questions/49380321/pg-restore-cant-import-data-if-table-has-a-constraint-with-a-function-calling
https://bucardo.org/postgres_all_versions.html#version_9.3.22
https://www.postgresql.org/message-id/flat/152153826367.11956.8092048336300020216%40wrigleys.postgresql.org
> Make schema pg_dump-able

- cnxdb/migrations/20180816162942_fix-function-ownership.py
Production somehow has different ownership for these eight functions than happens from a fresh 
DB deployment. This code fixes them.
> fix production functions with wrong owner

- cnxdb/archive-sql/schema/common-functions.sql
- cnxdb/archive-sql/schema/legacy_collxml.sql
- cnxdb/archive-sql/schema/manifest.json
- cnxdb/migrations/20180912153344_add-collxml-funcs.py
This is a set of database functions that can generate a valid collxml from the modules and trees tables. Particularly useful for minor-version collections that do not have a legacy-generated collxml (or for regenerating ones that are invalid) See attached issue for potential uses.
> Generate collxml

- .dockerignore
- .jenkins/deploy
This automates the building of the docker container and python distribution on release.
On a typical merge build this will build an `openstax/cnx-db:dev` image. The `openstax/cnx-db:dev` image should therefore always represent the tip of `master`. That image is also released as `openstax/cnx-db:${version}` when a tag is created.
When a tag is created this will release the `cnx-db-${version}.whl` (Python Wheel) to pypi.org.
Note, this pull request is setup to work against the test instance of PyPI. This will test that part of this configuration prior to us using it. After we've verified it works, we can remove the `FIXME` and `--repository-url https://test.pypi.org/legacy/` option to twine.
Addresses https://github.com/openstax/quality-assurance-meta/issues/82
> Build the Docker image and Python distribution

- .jenkins/deploy
Use the pypi creds for user & password
Fix the mount point for mounting the .git directory, which is actually in the $WORKSPACE, not $PWD.
> Fix jenkinsfile release rules

- cnxdb/migrations/20180926215317_set-canonical.py
- cnxdb/migrations/20181023135904_build-collxml.py
The collxml builder migration has an outright bug. The canonical setter migration is overly aggressive. This PR fixes both.
> Migration fixes

- .dockerfiles/initdb.d/00_initdb.sh
- Dockerfile
- docker-compose.yml
Upstream changes have made it so the `postgres` role is no longer created
along with the `$POSTGRES_USER`, which defaults to `postgres`.
Because of this, we'll stick with the default and create our superuser
in the init script.
These changes should keep things the same, just reorder them slightly.
This will hopefully resolve the issue @BryanEliDimas is seeing on Travis for Press (and Archive). That problem I believe has to do with upstream security updates that have changed how the container functions. We've run into this kind of thing before. The upstream container `openstax/postgres:9.4` has been updated. But the update also has upstream changes to `$POSTGRES_USER` behavior, which is why these changes have been created.
> Adjust the container POSTGRES_USER value

- cnxdb/contrib/pytest.py
This fixes `RemovedInPytest4Warning: Fixture "db_init" called directly. Fixtures are not meant to be called directly, are created automatically when test functions request them as parameters. See https://docs.pytest.org/en/latest/fixture.html for more information.` which is being raised during cnx-publishing tests, which is causing `master` to fail.
> Fix RemovedInPytest4Warning in dependent code

- cnxdb/archive-sql/schema/manifest.json
- cnxdb/archive-sql/schema/type_utility_functions.sql
- cnxdb/migrations/20181116174628_correct-canonical.py
This PR includes support functions  (book_pages and set_canonical) that are then used by a data migration to set the canonical book uuid for all pages in the OpenStax books that share pages.
Analysis of the requested canonical settings reveals that the required set of canonicals can be satisfied
by setting the pages in each of 5 books as the canonical book for all of the pages in it, thereby pointing the shared pages from other OS books to the primary 5.
Unfortunately, not all 5 primary books are independent: There exists a secondary dependency, where 2 of the 5 primary books share pages: in that case one of the two is selected as the primary primary. This means that setting canonical id on the pages must happen in a defined order: secondary canonical, then primary (including the …
> set canonical book uuids for OpenStax books

- Jenkinsfile
This does a simple test to standup the container, then make a connection to it
from another container. If the command executes without error
the pipeline continues.
This doesn't address when the base container becomes out-of-date.
That is likely a change outside the scope of this repo.
>  Check the container can receive connections before publishing it

- MANIFEST.in
- setup.py
When installing cnx-db, a global "tests" package is also installed.
That is probably not a good idea.  We can fix this by excluding tests in
setup.py.
Also remove tests settings from MANIFEST.in and setup.py.
> Exclude tests in find_packages() in setup.py

- cnxdb/archive-sql/schema/trees.sql
- cnxdb/migrations/20190502042501_create_trees_slug_column.py
- cnxdb/migrations/20190502042932_populate_trees_slug_values.py
- setup.py
This adds a column to the `trees` table where the REX URL path slug will be stored. See https://github.com/openstax/cnx/issues/348 for feature details.
The migration for that accompanies this change adds the new column to the `trees` table and assigns the slug path for existing baked book content.
> Add a column for the REX URL slug

- cnxdb/migrations/20190507211827_include_slug_in_tree_to_json.py
Depends on #178, which adds the slug column to the database. This adjusts the `tree_to_json` sql function, which is used for displaying the *book table-of-contents*.
This change will directly influence cnx-archives response data for book based content. The integration tests within archive will need to be updated to address the change made here.
>  Include the slug value in tree_to_json results 

- cnxdb/migrations/20170911201035_transform_cnxml_to_html.py
- setup.py
We transformed the content in the database but the old content continues
to be served because we don't purge the varnish cache.  This purges
everything under /contents/ in archive just to be sure.  Updates to
cnxml-to-html transforms isn't that frequent, and when it is performed,
it is for all the content in the database anyway so this should be ok.
> Purge varnish cache after transforms

- script/dump_book.py
This script attempts to dump a book from the server and load it into a
development database.
1. You need to download this script onto the server, e.g. staging08.cnx.org,
that runs archive.
2. Use `./dump_book.py dump_book caa57dab-41c7-455e-bd6f-f443cda5519c@19.3` to
dump the prealgebra book.
2.1 If you are not using this on a cnx-deploy'd server, you can either
specify the path to the archive config file using `CONFIG_INI` or the
database connection string using `DB_URL` environment variables.
2.2 If you want to dump multiple books, just add more book ident hashes to
the end of the command line.
3. Transfer the output file
`book_dump.prealgebra@19.3.tar` to the
development machine.
4. Run `./dump_book.py load_book book_dump.prealgebra@19.3.tar`
to load the book into a development …
> Add script/dump_book.py to dump/load a book from db

- requirements/lint.txt
docutils 0.15 breaks bin/doc8:
```
/home/travis/build/openstax/cnx-db/.state/env/bin/python bin/doc8 README.rst docs/
Traceback (most recent call last):
File "bin/doc8", line 8, in <module>
import doc8.main
File "/home/travis/build/openstax/cnx-db/.state/env/lib/python2.7/site-packages/doc8/main.py", line 48, in <module>
from doc8 import checks
File "/home/travis/build/openstax/cnx-db/.state/env/lib/python2.7/site-packages/doc8/checks.py", line 21, in <module>
from docutils import nodes as docutils_nodes
File "/home/travis/build/openstax/cnx-db/.state/env/lib/python2.7/site-packages/docutils/nodes.py", line 32, in <module>
import docutils.utils
File "/home/travis/build/openstax/cnx-db/.state/env/lib/python2.7/site-packages/docutils/utils/__init__.py", line 20, in <module>
from docutils …
```
> Pin docutils to 0.14 in requirements/lint.txt

- cnxdb/migrations/20190502042932_populate_trees_slug_values.py
- setup.py
- Repeat populate tree slug migration
We adjusted our implementation of generating slugs in cnx-common so we
need to regenerate all the slugs in the database.
Adding `should_run` in `populate_trees_slug_values` migration means that
dbmigrator is going to check it to see if this migration should run.
The condition is based on the bug report we received: if the slug for
`Astronomy` -> `2 Observing the Sky: The Birth of Astronomy` ->
`Exercises` -> `Review Questions` is `review-questions` (instead of
`2-review-questions`), the migration should run.
We can remove the `should_run` from this migration once this has been
deployed to prod.
- Add cache purging code to populate trees slug migration
We need to not use the cached result and get archive to generate the
results to be up to date.
> Repopulate tree slug values

- .travis.yml
- script/ci_check_dist.sh
To avoid tagging and then getting rejected by pypi, we're running twine
check on travis so it will catch all the errors before we upload to
pypi.
> Add twine check on travis

- cnxdb/contrib/pytest.py
In cnx-press, the `db_tables` fixture is used as a session fixture
instead of a function fixture but pytest 4.1.0 make it an error to call
a fixture:
```
Fixture "db_tables" called directly. Fixtures are not meant to be called directly,
but are created automatically when test functions request them as parameters.
See https://docs.pytest.org/en/latest/fixture.html for more information about fixtures, and
https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly about how to update your code.
```
One of the solutions suggested by pytest is to separate the function that has
the fixture decorator and the function that returns the fixture.
This fixes cnx-press so it can use the latest version of pytest.
> Separate db_tables function and fixture for reuse
