openstax/cnx-db

cnxdb/archive-sql/get-collated-content.sql, cnxdb/archive-sql/get-collated-state.sql, cnxdb/archive-sql/get-content-from-legacy-id-ver.sql, cnxdb/archive-sql/get-content-from-legacy-id.sql, cnxdb/archive-sql/get-featured-links.sql, cnxdb/archive-sql/get-in-book-search-full-page.sql, cnxdb/archive-sql/get-in-book-search.sql, cnxdb/archive-sql/get-in-collated-book-search-full-page.sql, cnxdb/archive-sql/get-in-collated-book-search.sql, cnxdb/archive-sql/get-module-metadata.sql, cnxdb/archive-sql/get-module-versions.sql, cnxdb/archive-sql/get-module.sql, cnxdb/archive-sql/get-resource-by-filename.sql, cnxdb/archive-sql/get-resourceid-by-filename.sql, cnxdb/archive-sql/schema/fulltext-indexing.sql, cnxdb/archive-sql/schema/functions.sql, cnxdb/archive-sql/schema/indexes.sql, cnxdb/archive-sql/schema/tables.sql, cnxdb/archive-sql/schema/tree_to_json.sql, cnxdb/archive-sql/schema/trees.sql, cnxdb/migrations/20160909180928_in-collated-book-search.py, cnxdb/migrations/20160923184915_correct_uuid_index.py, cnxdb/migrations/20160928202728_fulltext-collated-triggers.py
Latest database schema and SQL changes updated from cnx-archive.
=> Archive update

cnxdb/archive-sql/schema/functions.sql, cnxdb/migrations/20170208213802_ident-hash-func.py
=> Ident hash

cnxdb/archive-sql/schema/triggers.sql, cnxdb/migrations/20170313205225_rebake-trigger.py
Adds a trigger that notices when a ruleset.css is pushed, and sets the appropriate post-production state, to trigger the on-server baking of the associated book
=> Rebake trigger

cnxdb/archive-sql/get-in-collated-book-search.sql, cnxdb/archive-sql/schema/indexes.sql, cnxdb/migrations/20170523212842_fast-in-book-search.py
ran cnx-archive tests as well (which is where the search code is actually tested) and they pass.
=> speed up in book search for collated content

cnxdb/archive-sql/schema/indexes.sql, cnxdb/migrations/20170530143035_search-modtags-index.py
added index to moduletags so the sql runs faster for the full search of the cnx archive.
Changed local runs of the sql code to go from approximately 45 sec to 3 sec.
=> added index to moduletags

cnxdb/archive-sql/schema/tables.sql, cnxdb/archive-sql/schema/triggers.sql, cnxdb/migrations/20170614211640_print-style-recipes.py
Add table and columns to track recipes via print styles, as well as track most recent successfully used recipe.
=> Print style recipes

cnxdb/migrations/20170614211640_print-style-recipes.py
@sisiz fixing my broken code. :+1:
=> migrations fix

cnxdb/archive-sql/get-books-containing-page.sql
Addresses [#499 in cnx-archive](https://github.com/Connexions/cnx-archive/issues/499). 
Sibling PR [here in cnx-archive](https://github.com/Connexions/cnx-archive/compare/get-books-containing-page), which implements a route and view to run this query.
=> Implement get books containing a given page

cnxdb/archive-sql/schema/triggers.sql, tests/schema/test_triggers.py
This is to solve a race condition in the update_latest trigger because
of two inserts happening at the same time:
```
Traceback (most recent call last):
File "/var/cnx/venvs/publishing/src/cnx-publishing/cnxpublishing/subscribers.py", line 106, in baking_processor
bake(binder, recipe_id, publisher, message, cursor=cursor)
File "/var/cnx/venvs/publishing/src/cnx-publishing/cnxpublishing/db.py", line 61, in wrapped
return func(*args, **kwargs)
File "/var/cnx/venvs/publishing/src/cnx-publishing/cnxpublishing/bake.py", line 81, in bake
publish_composite_model(cursor, doc, binder, publisher, message)
File "/var/cnx/venvs/publishing/src/cnx-publishing/cnxpublishing/publish.py", line 375, in publish_composite_model
publisher, message)
File …
```
=> Lock latest_modules when running update_latest

cnxdb/migrations/20170821163229_update_latest_trigger.py
=> Add migration for update_latest function

cnxdb/archive-sql/xpath-module.sql, cnxdb/archive-sql/xpath.sql, docs/changes.rst
Sibling to [xpath-extension in cnx-archive.](https://github.com/Connexions/cnx-archive/pull/506)
=> Xpath extension

.travis.yml, .travis_test_migrations.sh
Compare the schema before and after migration and rollback to make sure
migrations match the schema.
=> Add migration and rollback tests in travis

cnxdb/archive-sql/schema/indexes.sql, cnxdb/archive-sql/schema/legacy/indexes.sql, cnxdb/archive-sql/schema/tables.sql, cnxdb/migrations/20170912184444_foreign-key-idx.py, cnxdb/publishing-sql/schema-indexes.sql, cnxdb/publishing-sql/schema-tables.sql
This supports rapid deletion from modules table.
=> add delete cascade and indexes for foreign keys

cnxdb/archive-sql/schema/legacy/triggers.sql, cnxdb/migrations/20170912141914_derived-ruleset-trig.py
=> need to return something

cnxdb/archive-sql/get-books-containing-page.sql, cnxdb/archive-sql/schema/functions.sql, cnxdb/migrations/20171005213556_first-last.py, script/ci_test_migrations.sh
This will be used for page extras, so even if the page being viewed is not the latest, it will accurately list the older books it is contained in.
=> get only the highest version book for each book a page is in

cnxdb/archive-sql/schema/views.sql, cnxdb/migrations/20171025183429_all-currrent-view.py
Needed for finding books that are associated w/ a particular recipe/print_style, but have failed to bake.
PR https://github.com/Connexions/cnx-publishing/pull/164 depends on this
=> a view of all most recent content, regardless of baked state

.dockerfiles/initdb.d/initdb.sh, docker-compose.yml
This adds DB_URL and DB_SUPER_URL to the docker container configuration.
=> Fix docker-compose to use env vars

cnxdb/init/main.py
This comes from out-of-scope requests for change on #98 by @reedstrm.
=> Touchup the docstrings for database init functions

cnxdb/contrib/pyramid.py, docs/changes.rst, docs/index.rst, docs/usage.rst
This more or less simply adds some docs for how to use the pyramid integration without previously knowing what you're doing.
=> Provide some usage docs for pyramid integration

cnxdb/archive-sql/get-books-containing-page.sql
changed the sql to get the author full names, first name, surname, title suffix  along with the userid. also gets revision date
goes along with changes made on cnx-archive on extras-authors branch
=> Add author names to Books-containg-page

cnxdb/archive-sql/get-books-containing-page.sql
Update on sql for getting info about the books a single page is in
=> return shortid as well

Makefile
Simple fix to the pyenv recipe
=> Correct the python 2 virtual env (pyenv) recipe

.github/settings.yml
- Enable squash merging over rebase merging
- Set a few of the common settings
=> Add github settings file

cnxdb/archive-sql/schema/triggers.sql, cnxdb/migrations/20180818033715_fix-html-abstracts.py
Trigger broke when html already exists (caught in archive test)
=> use correct type for temp variable in trigger test

docs/changes.rst
=> Fix changelog line too long

cnxdb/archive-sql/schema/legacy/tables.sql, cnxdb/archive-sql/schema/legacy/triggers.sql, cnxdb/migrations/20180913191159_legacy-passwd-sync.py
need a place to store the auth info copied from legacy
=> add columns for legacy auth info

cnxdb/migrations/20181016204225_immutable_strict_funcs.py
=> need superuser for plpythonu funcs

cnxdb/archive-sql/schema/legacy_collxml.sql, cnxdb/migrations/20181107212026_replace_collxml_fn.py
this allows regenerating the collxml for any collection, in place in the DB.
=> add replace_collxml function

script/dump_book.py
I assumed that the first module_ident returned in
`get_module_idents_tree_nodes` is the book module ident, which I then
use to download `collated_file_associations`.  This is an incorrect
assumption probably due to `SELECT DISTINCT` in the sql in
`get_module_idents_tree_nodes`.  Because of this,
`collated_file_assocations` is empty.
To fix this, change `get_module_idents_tree_nodes` to order by `parent`
descending, which should get the book, with `parent` null, to the top.
=> Fix empty collated file associations in dump_book.py

cnxdb/migrations/20170911201035_transform_cnxml_to_html.py
Whenever rhaptos.cnxmlutils is updated, transforms is run automatically.
But only the raw html is updated, the baked html is untouched.  The raw
html isn't what we serve for most of the openstax books, so we have to
rebake the books to make sure the changes also get to the baked html.
=> Rebake books in cnxml-to-html transforms migration

cnxdb/migrations/20170911201035_transform_cnxml_to_html.py
In the transforms (cnxml-to-html) migration, originally, we rebake all
books that have outdated pages.  There were so many and baking took too
long that we decided to limit rebaking to latest openstax books.
---
Using this query, there are only 66 books on staging that match.
=> Rebake only latest openstax books in transforms migration

script/create_person.py, script/dump_book.py
- create_person creates a fake legacy user with password
- Reduce uniqueness error frequency with dump_book loading
- Make sure sequences will not conflict post-bake
=> Ease seeding db from an empty volume
